import os

os.system("find enclave/ -type f -name '*.o' -delete")
os.system("rm -r output")
os.system("rm -r generated")
os.system("rm -r lib_harness")
os.system("rm -r *.so")
os.system("rm -r test.db")
os.system("rm -r test.db-journal")
os.system("rm -r test-nowrap.db")
os.system("rm -r test.dbserver.db")
os.system("rm -r test-nowrap.db-journal")
os.system("rm -r test-nocrypt.db")
os.system("rm -r test-nocrypt.db-journal")
os.system("rm -r valgrind.output.log")
os.system("rm -r test.file.test")
os.system("rm -r runtest")
os.system("rm -r Makefile")
os.system("find unit_tests/ -type f -name '*.o' -delete")
os.system("find src/ -type f -name '*.o' -delete")
os.system("find scripts/ -type f -name '*.pyc' -delete")
os.system("rm Makefile*")
os.system("rm telemetry.log")

